### ISSUE TITLE
`npm update ractive` downgrades ractive rather than upgrading

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3096]
## Description:

When I update from 1.0.0-build-66 to 1.0.0-build-9, I get the following error when I click a button in my application: 

```js
ctx.getParent is not a function
```

Unfortunately, I'm not able to reproduce the same problem via https://github.com/ractivejs/ractive/issues/3067#issuecomment-328033011

**Comment by ceremcem** [comment]
According to the build dates, 1.0.0-build-66 is newer than 1.0.0-build-9, but `npm update ractive` removes 1.0.0-build-66 and installs 1.0.0-build-9. Is there any way to fix that problem?

```bash
ceremcem@cca-erik:a$ npm i ractive@edge --save
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN a@1.0.0 No description
npm WARN a@1.0.0 No repository field.

+ ractive@1.0.0-build-69
added 1 package in 81.676s
ceremcem@cca-erik:a$ npm update ractive
^C^C
ceremcem@cca-erik:a$ grep ractive package.json 
    "ractive": "^1.0.0-build-69"
ceremcem@cca-erik:a$ npm update ractive
npm WARN a@1.0.0 No description
npm WARN a@1.0.0 No repository field.

+ ractive@1.0.0-build-9
updated 1 package in 0.58s
ceremcem@cca-erik:a$ 
```

**Comment by evs-chris** [comment]
npm is confused because it's doing string rather than number comparisons for the build versions. I don't know that there's a good way to get automatic updates from npm before a full release.

**Comment by ghost** [comment]
_left-pad_ by 3 digits. (see what I did there?) 😁 

But yeah, it will think 9 is later.

**Comment by ghost** [comment]
We could release 0.10 and start over the count (since we can't go past 9 unless we release starting with 900). This time, we pad the numbers sufficiently.

"Feature release: Better dev build numbers. 😁 "

**Comment by ceremcem** [comment]
Could you publish the current release with `1.0.0-build-900` again and increment by one for each next?
