### ISSUE TITLE
Rebinding error on splice of an array driving radio buttons with the same attribute name

### ISSUE THREAD

**Issue by mnogueron** [ractivejs/ractive#2939]
### Context:
Considering a list of objects as data given to a for each template, each object has an attribute `selectedRadio` driving the state of a list of radio buttons
### Issue:
When removing an object from this list with `ractive.splice`, this one is correctly removed from the data but the rendering update fails with `TypeError: this$1.deps[i].rebinding is not a function`

However using `elements[i].selectedRadio` instead of just `selectedRadio` works well.
### Expected behaviour:
Using `selectedRadio` should work the same way as `elements[i].selectedRadio`.

## Versions affected:

At least `0.8.1`, works correctly with `0.7.3`

## Reproduction:

JSFidle not working - `selectedRadio` : [http://jsfiddle.net/xpew028d/](http://jsfiddle.net/xpew028d/)
JSFidle working - `elements[i].selectedRadio` : [http://jsfiddle.net/at6f83jL/](http://jsfiddle.net/at6f83jL/)

## Code:

```
  {{#each elements:i}}
  <form>
    <input type="radio" name="{{selectedRadio}}" value="1" checked>1<br>
    <input type="radio" name="{{selectedRadio}}" value="2">2<br>
    <input type="radio" name="{{selectedRadio}}" value="3">3<br>
    <button type="button" onclick="removeRow({{i}})">Remove row {{i}}</button>
  </form>
  {{/each}}
```
```
var ractive = new Ractive({
    el: 'main',
    template: '#template',
    data: {
        elements: [
          { selectedRadio: "1" },
          { selectedRadio: "1" },
          { selectedRadio: "1" },
          { selectedRadio: "1" },
          { selectedRadio: "1" }
        ]
    }
});
```

**Comment by evs-chris** [comment]
This is now fixed in v0.8-dev and edge and will go out with 0.8.13 when it's cut. Thanks for the report!
