### ISSUE TITLE
Strange issue with a partial inside iterator

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#3145]
See this case https://jsfiddle.net/Inversion/ukc7deey/
It throws: Uncaught TypeError: fragment.context.has is not a function
Problem caused by `{{>cleared_v k}}` in line 11.
If you replace it with `{{>cleared_v 'k'}}` — it will work.

Same for: 0.8-dev, 0.9-dev, edge.
Worked fine in 0.7

**Comment by evs-chris** [comment]
The issue is that a key is strictly scalar and can't have downstream keypaths. When passed as a context, the resolution process tries to check for a downstream path for the ambiguous `cleared_v` and can't because key models don't support the check. I've added a noop handler to get around the exception on edge and I'll backport it to 0.9 and 0.8 in a bit. Thanks for the report!
